monolog:
    handlers:
        applog:
            type: rotating_file
            max_files: 30
            level: error
        main:
            type: rotating_file
            max_files: 30
            action_level: warning
            handler: file
        file:
            type: rotating_file
            max_files: 30
            level: debug
        syslog:
            type: syslog
            level: error

oneup_flysystem:
    adapters:
        local_filesystem_adapter:
            local:
                directory: "%kernel.root_dir%/../var/cache/%kernel.environment%/response"

    filesystems:
        local:
            adapter: local_filesystem_adapter
            
cache_adapter:
  providers:    
    file_system_provider:
      factory: 'cache.factory.filesystem'
      options:
        flysystem_service: 'oneup_flysystem.local_filesystem'
    redis_wrapper_provider:
      factory: 'cache.factory.redis'
      options:
        host: 127.0.0.1
        port: 6379
        
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: "%kernel.debug%"
    #bundles:        "%bundles%"
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: "%kernel.root_dir%/../vendor/mcmaroon/app-bundle/Lib/UglifyJS/bin/uglifyjs"
        uglifycss:
            bin: "%kernel.root_dir%/../vendor/mcmaroon/app-bundle/Lib/UglifyCSS/uglifycss"
    assets:
        jquery_js:
            inputs:
                - '@AppAppBundle/Resources/public/js/jquery/jquery.min.js'
                - '@AppAppBundle/Resources/public/js/jquery/jquery-ui.min.js'
        bootstrap_js:
            inputs:
                - '@AppAppBundle/Resources/public/js/bootstrap4/vendor/popper.min.js'
                - '@AppAppBundle/Resources/public/js/bootstrap4/util.js'
                - '@AppAppBundle/Resources/public/js/bootstrap4/alert.js'
                - '@AppAppBundle/Resources/public/js/bootstrap4/button.js'
                - '@AppAppBundle/Resources/public/js/bootstrap4/carousel.js'
                - '@AppAppBundle/Resources/public/js/bootstrap4/collapse.js'
                - '@AppAppBundle/Resources/public/js/bootstrap4/dropdown.js'                
                - '@AppAppBundle/Resources/public/js/bootstrap4/modal.js'                
                - '@AppAppBundle/Resources/public/js/bootstrap4/scrollspy.js'                
                - '@AppAppBundle/Resources/public/js/bootstrap4/tab.js'
                - '@AppAppBundle/Resources/public/js/bootstrap4/tooltip.js'
                - '@AppAppBundle/Resources/public/js/bootstrap4/popover.js'                
                #- '@AppAppBundle/Resources/public/js/bootstrap4/bootstrap.min.js'                
                
        plugin_js:
            inputs:
                - '@AppAppBundle/Resources/public/js/plugin/jquery.growl.js'
                - '@AppAppBundle/Resources/public/js/plugin/jquery.highlighttext.js'
                - '@AppAppBundle/Resources/public/js/plugin/jquery.lazyload.js'
                - '@AppAppBundle/Resources/public/js/plugin/owl.carousel.js'
                - '@AppAppBundle/Resources/public/js/plugin/chosen.js'
                - '@AppAppBundle/Resources/public/js/plugin/gmap3.min.js'
                - '@AppAppBundle/Resources/public/js/plugin/floatThead.js'
                - '@AppAppBundle/Resources/public/js/plugin/socket.io.js'
                - '@AppAppBundle/Resources/public/js/plugin/vis.js'
        admin_js:
            inputs:
                - '@AppAppBundle/Resources/public/js/app/app.js'
                - '@AppAppBundle/Resources/public/js/app/growl.js'
                - '@AppAppBundle/Resources/public/js/app/sortable.js'
                - '@AppAppBundle/Resources/public/js/app/preview.js'
                - '@AppAppBundle/Resources/public/js/app/progress.js'
                - '@AppAppBundle/Resources/public/js/app/uploadmultiple.js'
                - '@AppAppBundle/Resources/public/js/app/map.js'
                - '@AppAppBundle/Resources/public/js/admin.js'        
        admin_css:
            inputs:
                - '@AppAppBundle/Resources/public/css/admin.css'
        preloader:
            inputs: '@AppAppBundle/Resources/public/images/preloader.gif'
            output: 'css/images/preloader.gif'
        glyphicons-halflings-eot:
            inputs: '@AppAppBundle/Resources/public/fonts/glyphicons-halflings-regular.eot'
            output: 'css/fonts/glyphicons-halflings-regular.eot'
        glyphicons-halflings-svg:
            inputs: '@AppAppBundle/Resources/public/fonts/glyphicons-halflings-regular.svg'
            output: 'css/fonts/glyphicons-halflings-regular.svg'
        glyphicons-halflings-ttf:
            inputs: '@AppAppBundle/Resources/public/fonts/glyphicons-halflings-regular.ttf'
            output: 'css/fonts/glyphicons-halflings-regular.ttf'
        glyphicons-halflings-woff:
            inputs: '@AppAppBundle/Resources/public/fonts/glyphicons-halflings-regular.woff'
            output: 'css/fonts/glyphicons-halflings-regular.woff'
        glyphicons-halflings-woff2:
            inputs: '@AppAppBundle/Resources/public/fonts/glyphicons-halflings-regular.woff2'
            output: 'css/fonts/glyphicons-halflings-regular.woff2'
        font-awesome-otf:
            inputs: '@AppAppBundle/Resources/public/fonts/FontAwesome.otf'
            output: 'css/fonts/FontAwesome.otf'
        font-awesome-eot:
            inputs: '@AppAppBundle/Resources/public/fonts/fontawesome-webfont.eot'
            output: 'css/fonts/fontawesome-webfont.eot'
        font-awesome-svg:
            inputs: '@AppAppBundle/Resources/public/fonts/fontawesome-webfont.svg'
            output: 'css/fonts/fontawesome-webfont.svg'
        font-awesome-ttf:
            inputs: '@AppAppBundle/Resources/public/fonts/fontawesome-webfont.ttf'
            output: 'css/fonts/fontawesome-webfont.ttf'
        font-awesome-woff:
            inputs: '@AppAppBundle/Resources/public/fonts/fontawesome-webfont.woff'
            output: 'css/fonts/fontawesome-webfont.woff'
        font-awesome-woff2:
            inputs: '@AppAppBundle/Resources/public/fonts/fontawesome-webfont.woff2'
            output: 'css/fonts/fontawesome-webfont.woff2'
        jquery-ui-sprite-444444:
            inputs: '@AppAppBundle/Resources/public/images/jquery-ui/ui-icons_444444_256x240.png'
            output: 'css/images/ui-icons_444444_256x240.png'
        jquery-ui-sprite-555555:
            inputs: '@AppAppBundle/Resources/public/images/jquery-ui/ui-icons_555555_256x240.png'
            output: 'css/images/ui-icons_555555_256x240.png'
        chosen-sprite:
            inputs: '@AppAppBundle/Resources/public/images/chosen-sprite.png'
            output: 'css/images/chosen-sprite.png'
        chosen-sprite2x:
            inputs: '@AppAppBundle/Resources/public/images/chosen-sprite@2x.png'
            output: 'css/images/chosen-sprite@2x.png'

# Doctrine Configuration
doctrine:
    dbal:
        # http://blog.kowalczyk.cc/2013/01/25/doctrine2-blad-unknown-database-type-enum-requested-mysqlplatform-may-not-support-it/
        mapping_types:
            enum: string
    orm:
        dql:
            string_functions:
                IF: App\AppBundle\Doctrine\Extension\IfElse 
                GROUP_CONCAT: App\AppBundle\Doctrine\Extension\GroupConcat
                LEVENSHTEIN: App\AppBundle\Doctrine\Extension\Levenshtein
                LEVENSHTEIN_RATIO: App\AppBundle\Doctrine\Extension\LevenshteinRatio
                DATE: App\AppBundle\Doctrine\Extension\Date
                MATCH_AGAINST: App\AppBundle\Doctrine\Extension\MatchAgainst
            numeric_functions:
                ROUND: App\AppBundle\Doctrine\Extension\Round
                ACOS: App\AppBundle\Doctrine\Extension\Acos
                COS: App\AppBundle\Doctrine\Extension\Cos
                SIN: App\AppBundle\Doctrine\Extension\Sin
                RADIANS: App\AppBundle\Doctrine\Extension\Radians
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true

# StofDoctrineExtensionsBundle Configuration
stof_doctrine_extensions:
    orm:
        default:
            softdeleteable: true
            translatable: true
            sluggable: true

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

knp_menu:
    twig:
        template: AppAppBundle:Default:knp_menu.html.twig

# LiipImagineBundle Configuration
liip_imagine:
    driver: gd
    filter_sets:
        thumb_admin_default:
            animated: true
            quality: 75
            filters:
                relative_resize:
                    scale: 1.0
        thumb_admin_small:
            animated: true
            quality: 75
            filters:
                upscale: { min: [60, 30] }
                thumbnail: { size: [60, 30], mode: outbound }
        thumb_admin_medium:
            animated: true
            quality: 75
            filters:
                upscale: { min: [120, 60] }
                thumbnail: { size: [120, 60], mode: outbound }
        thumb_admin_large:
            animated: true
            quality: 75
            filters:
                upscale: { min: [480, 240] }
                thumbnail: { size: [480, 240], mode: outbound }