admin_helper_preview:
    path:     /helpers/preview/{entityNamespace}/{id}/{templatePart}
    defaults: { _controller: "AppAppBundle:AdminHelper:preview", entityNamespace: "DefaultEntity", id: 0, templatePart: "" }
    
admin_helper_sort:
    path:     /helpers/sort/{entityNamespace}
    defaults: { _controller: "AppAppBundle:AdminHelper:sort", entityNamespace: "DefaultEntity" }