services:

    MCSF\HelperBundle\Twig:
        class: MCSF\HelperBundle\Twig\ParameterExtension
        arguments: ["@service_container"]
        public: false
        tags:
        - { name: twig.extension }
